## paradata - Module 4

### Macro - The Bigger Picture
  Interestingly, this project was not terribly different in its purpose to the previous module. Though it did involve bringing a digital object “into the physical world”, our project was heavily reliant on user interaction to create the experience we wanted to display. It could be potentially described as a very simple “active narrative” node - one with only two alternating options - due to the fact that the viewer has the ability to change the view of the model at their own will and pacing (Copplestone, T. and Dunne, D. 2017). We have a slight worry that our project may be subject to similar criticisms as those made by Stuart Eve in his article against Pokémon Go, as he claimed it was the “most basic AR” possible (Eve). Like the Pokémon in Pokémon Go, our 3D models don’t really interact with the physical environment the viewer finds themself in - they only interact with the viewer, and only in the simplest manner, switching views in accordance with the viewer’s tapping their phone screen. Is this true “augmented reality”?

Perhaps our augmented reality experience is only barely “augmented reality” (in addition to its being “barely functional” - see the micro section); however, we ran into so many technical difficulties along the way in attempting to set up our display that we now wonder if we would have even had the ability to create anything more complex within the module’s time frame. This was probably one of the modules in which we felt our lack of experience with the technology infringing the most on our ability create a complex, meaningful project.

Theoretically, if our project had worked the way we intended it to, the viewer would have been able to switch between views of the 3D model of our statue in two modes: one of its “past” state, in which the model’s legs were broken off in an approximation of how it was found during its original excavation and one of its “present” state with its legs re-attached. It is almost comical that HP Reveal’s augmented reality displays are referred to on the site as “Auras”, as the augmented reality experience we constructed directly confronts the “aura” (in Latour & Lowe’s conception of the word) of the “original” version, allowing for expansion on the meaning of the original object by revealing alternate “possibilities” for its being (Latour & Lowe, 2011). Given the ability to alternate between these possibilities, the viewer might come away with an expanded conception of the “aura” of the original statue now that they have been able to visualize it both fractured and whole. It remains an advantage that no actual physical object needs to be damaged or repaired in order for these visualizations to be observed.

We tried to be aware of how colonialism was inherent in our project. William is an Ancient Egyptian hippopotamus and was created out of a material that is specific to Ancient Egypt. He was excavated by German archaeologists and then was eventually sold to a rich American who donated him and many other artifacts to the Metropolitan Museum of Art in the early 20th century. Although we did not work with the “original” William, but rather an authorized replica obtained at a gift store, we had to take into account the implications that came with it and even the idea of there being an “authorized copy” of such an artifact. We did not know much about the original object other than its being an Ancient Egyptian artifact. The more we learned about William, the more we considered the idea of repatriation of artifacts to their origin. Is it even worth the effort of repatriation when the culture that this object is significant to is gone? Who does William belong to? Is it the Metropolitan Museum of Art who have had him since 1931 or is the ancestors of those who created him? The fact that he was even given the nickname of “William” is important to note in terms of colonialism because it is an English name given to an African object that was excavated by German archaeologists. He has been exchanged numerous times, and although his origin is known, does it matter anymore? To our knowledge, nobody is asking for his repatriation unlike other more modern objects. Digitizing him could be an interesting way to repatriate objects...but then the object’s authenticity can be questioned. Additionally, museums could still employ gate-keeping tactics through their claims of “having the real thing”. 

One further concern we had with regard to possibilities of “digital colonialism” in our modules was whether or not our projects focused too heavily around the narrative of the colonial excavation of William as an artifact for display in Western museums. It could perhaps be argued that the object of the statue had a history beyond this single aspect of its existence, and it is only through the colonial gaze that its “discovery” by Western archaeologists is central to its history. However, it might also be argued that given the limited recorded information we have available on the statue, this narrative has limits as well; therefore it makes sense to focus on the colonial history of the object, especially if this history is endowed with a critical self-reflexivity that questions the ownership of the object. Finally, there may be questions as to whether depicting the statue with its legs restored is a form of erasing the past history, if we can determine that the legs were meant to be broken off for ceremonial purposes. The restoration of the legs is very much a convention of Western archaeology, taking the assumption that there is something “broken” about the object even if this was its intended state. Why might we have restored the legs of this Egyptian statue while neglecting to do the same for the arms of the Venus di Milo? There is a lot to think about, and we are just scratching the surface of the many problems to do with colonialism and artifacts.

### Micro - Process and Details
There were a number of difficult technical issues that turned up during the process of attempting to create the “Aura”. Even getting the initial .tar file to load as an overlay to load proved to be a difficult process; HP Reveal was not the most user-friendly platform - though we also had no prior experience in creating any kind of augmented reality experiences. Probably the single most frustrating problem with the creation of the display was that we still could not get the textures to load for the models by the end of the process, even when everything was worked exactly as we had planned it. We tried doing more research on this problem to see if other users had found solutions to it, but it seemed no one had, so there was little we could do to fix it. This highly limits the effectiveness of our display in terms of practical uses, since the intention of the display relies on the viewer being able to identify what they’re seeing as a specific object, as well as the changes that appear in that object when they modify it. Considering the two objects are unidentifiable textureless “clumps”, this will likely be impossible.

